sonar.projectKey=rushikeshsakharleofficial_server-inventory
sonar.organization=rushikeshsakharleofficial

sonar.projectName=ServerInventory
sonar.projectVersion=1.0

# Source roots
sonar.sources=backend/app,frontend/src
sonar.tests=frontend/e2e

# Exclusions
sonar.exclusions=\
  frontend/dist/**,\
  frontend/node_modules/**,\
  frontend/e2e/**,\
  **/__pycache__/**,\
  **/*.pyc,\
  frontend/playwright-report/**,\
  frontend/test-results/**

# Python
sonar.python.version=3.11

# TypeScript / JavaScript
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.typescript.tsconfigPath=frontend/tsconfig.json

# Encoding
sonar.sourceEncoding=UTF-8
