/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppSyncRouteImport } from './routes/_app.sync'
import { Route as AppSshKeysRouteImport } from './routes/_app.ssh-keys'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppServersRouteImport } from './routes/_app.servers'
import { Route as AppResourceMapRouteImport } from './routes/_app.resource-map'
import { Route as AppKubernetesRouteImport } from './routes/_app.kubernetes'
import { Route as AppDatabasesRouteImport } from './routes/_app.databases'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCronsRouteImport } from './routes/_app.crons'
import { Route as AppCredentialsRouteImport } from './routes/_app.credentials'
import { Route as AppBlockStoragesRouteImport } from './routes/_app.block-storages'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSyncRoute = AppSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AppRoute,
} as any)
const AppSshKeysRoute = AppSshKeysRouteImport.update({
  id: '/ssh-keys',
  path: '/ssh-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppServersRoute = AppServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => AppRoute,
} as any)
const AppResourceMapRoute = AppResourceMapRouteImport.update({
  id: '/resource-map',
  path: '/resource-map',
  getParentRoute: () => AppRoute,
} as any)
const AppKubernetesRoute = AppKubernetesRouteImport.update({
  id: '/kubernetes',
  path: '/kubernetes',
  getParentRoute: () => AppRoute,
} as any)
const AppDatabasesRoute = AppDatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCronsRoute = AppCronsRouteImport.update({
  id: '/crons',
  path: '/crons',
  getParentRoute: () => AppRoute,
} as any)
const AppCredentialsRoute = AppCredentialsRouteImport.update({
  id: '/credentials',
  path: '/credentials',
  getParentRoute: () => AppRoute,
} as any)
const AppBlockStoragesRoute = AppBlockStoragesRouteImport.update({
  id: '/block-storages',
  path: '/block-storages',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/block-storages': typeof AppBlockStoragesRoute
  '/credentials': typeof AppCredentialsRoute
  '/crons': typeof AppCronsRoute
  '/dashboard': typeof AppDashboardRoute
  '/databases': typeof AppDatabasesRoute
  '/kubernetes': typeof AppKubernetesRoute
  '/resource-map': typeof AppResourceMapRoute
  '/servers': typeof AppServersRoute
  '/settings': typeof AppSettingsRoute
  '/ssh-keys': typeof AppSshKeysRoute
  '/sync': typeof AppSyncRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/block-storages': typeof AppBlockStoragesRoute
  '/credentials': typeof AppCredentialsRoute
  '/crons': typeof AppCronsRoute
  '/dashboard': typeof AppDashboardRoute
  '/databases': typeof AppDatabasesRoute
  '/kubernetes': typeof AppKubernetesRoute
  '/resource-map': typeof AppResourceMapRoute
  '/servers': typeof AppServersRoute
  '/settings': typeof AppSettingsRoute
  '/ssh-keys': typeof AppSshKeysRoute
  '/sync': typeof AppSyncRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/block-storages': typeof AppBlockStoragesRoute
  '/_app/credentials': typeof AppCredentialsRoute
  '/_app/crons': typeof AppCronsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/databases': typeof AppDatabasesRoute
  '/_app/kubernetes': typeof AppKubernetesRoute
  '/_app/resource-map': typeof AppResourceMapRoute
  '/_app/servers': typeof AppServersRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/ssh-keys': typeof AppSshKeysRoute
  '/_app/sync': typeof AppSyncRoute
  '/_app/users': typeof AppUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/block-storages'
    | '/credentials'
    | '/crons'
    | '/dashboard'
    | '/databases'
    | '/kubernetes'
    | '/resource-map'
    | '/servers'
    | '/settings'
    | '/ssh-keys'
    | '/sync'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/block-storages'
    | '/credentials'
    | '/crons'
    | '/dashboard'
    | '/databases'
    | '/kubernetes'
    | '/resource-map'
    | '/servers'
    | '/settings'
    | '/ssh-keys'
    | '/sync'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/block-storages'
    | '/_app/credentials'
    | '/_app/crons'
    | '/_app/dashboard'
    | '/_app/databases'
    | '/_app/kubernetes'
    | '/_app/resource-map'
    | '/_app/servers'
    | '/_app/settings'
    | '/_app/ssh-keys'
    | '/_app/sync'
    | '/_app/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sync': {
      id: '/_app/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof AppSyncRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ssh-keys': {
      id: '/_app/ssh-keys'
      path: '/ssh-keys'
      fullPath: '/ssh-keys'
      preLoaderRoute: typeof AppSshKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/servers': {
      id: '/_app/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof AppServersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resource-map': {
      id: '/_app/resource-map'
      path: '/resource-map'
      fullPath: '/resource-map'
      preLoaderRoute: typeof AppResourceMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kubernetes': {
      id: '/_app/kubernetes'
      path: '/kubernetes'
      fullPath: '/kubernetes'
      preLoaderRoute: typeof AppKubernetesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/databases': {
      id: '/_app/databases'
      path: '/databases'
      fullPath: '/databases'
      preLoaderRoute: typeof AppDatabasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crons': {
      id: '/_app/crons'
      path: '/crons'
      fullPath: '/crons'
      preLoaderRoute: typeof AppCronsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/credentials': {
      id: '/_app/credentials'
      path: '/credentials'
      fullPath: '/credentials'
      preLoaderRoute: typeof AppCredentialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/block-storages': {
      id: '/_app/block-storages'
      path: '/block-storages'
      fullPath: '/block-storages'
      preLoaderRoute: typeof AppBlockStoragesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBlockStoragesRoute: typeof AppBlockStoragesRoute
  AppCredentialsRoute: typeof AppCredentialsRoute
  AppCronsRoute: typeof AppCronsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDatabasesRoute: typeof AppDatabasesRoute
  AppKubernetesRoute: typeof AppKubernetesRoute
  AppResourceMapRoute: typeof AppResourceMapRoute
  AppServersRoute: typeof AppServersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSshKeysRoute: typeof AppSshKeysRoute
  AppSyncRoute: typeof AppSyncRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBlockStoragesRoute: AppBlockStoragesRoute,
  AppCredentialsRoute: AppCredentialsRoute,
  AppCronsRoute: AppCronsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDatabasesRoute: AppDatabasesRoute,
  AppKubernetesRoute: AppKubernetesRoute,
  AppResourceMapRoute: AppResourceMapRoute,
  AppServersRoute: AppServersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSshKeysRoute: AppSshKeysRoute,
  AppSyncRoute: AppSyncRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
