/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersGroupsRouteImport } from './routes/_app.users-groups'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppSyncRouteImport } from './routes/_app.sync'
import { Route as AppStatsRouteImport } from './routes/_app.stats'
import { Route as AppSshKeysRouteImport } from './routes/_app.ssh-keys'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppServersRouteImport } from './routes/_app.servers'
import { Route as AppServerGroupsRouteImport } from './routes/_app.server-groups'
import { Route as AppResourceMapRouteImport } from './routes/_app.resource-map'
import { Route as AppProviderCredentialsRouteImport } from './routes/_app.provider-credentials'
import { Route as AppPoliciesRouteImport } from './routes/_app.policies'
import { Route as AppKubernetesRouteImport } from './routes/_app.kubernetes'
import { Route as AppIpsRouteImport } from './routes/_app.ips'
import { Route as AppEventLogsRouteImport } from './routes/_app.event-logs'
import { Route as AppDomainsRouteImport } from './routes/_app.domains'
import { Route as AppDomainCredentialsRouteImport } from './routes/_app.domain-credentials'
import { Route as AppDatabasesRouteImport } from './routes/_app.databases'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCronsRouteImport } from './routes/_app.crons'
import { Route as AppCloudProvidersRouteImport } from './routes/_app.cloud-providers'
import { Route as AppBlockStoragesRouteImport } from './routes/_app.block-storages'
import { Route as AppServerDetailIdRouteImport } from './routes/_app.server-detail.$id'
import { Route as AppPoliciesSlugRouteImport } from './routes/_app.policies.$slug'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersGroupsRoute = AppUsersGroupsRouteImport.update({
  id: '/users-groups',
  path: '/users-groups',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppSyncRoute = AppSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppSshKeysRoute = AppSshKeysRouteImport.update({
  id: '/ssh-keys',
  path: '/ssh-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppServersRoute = AppServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => AppRoute,
} as any)
const AppServerGroupsRoute = AppServerGroupsRouteImport.update({
  id: '/server-groups',
  path: '/server-groups',
  getParentRoute: () => AppRoute,
} as any)
const AppResourceMapRoute = AppResourceMapRouteImport.update({
  id: '/resource-map',
  path: '/resource-map',
  getParentRoute: () => AppRoute,
} as any)
const AppProviderCredentialsRoute = AppProviderCredentialsRouteImport.update({
  id: '/provider-credentials',
  path: '/provider-credentials',
  getParentRoute: () => AppRoute,
} as any)
const AppPoliciesRoute = AppPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AppRoute,
} as any)
const AppKubernetesRoute = AppKubernetesRouteImport.update({
  id: '/kubernetes',
  path: '/kubernetes',
  getParentRoute: () => AppRoute,
} as any)
const AppIpsRoute = AppIpsRouteImport.update({
  id: '/ips',
  path: '/ips',
  getParentRoute: () => AppRoute,
} as any)
const AppEventLogsRoute = AppEventLogsRouteImport.update({
  id: '/event-logs',
  path: '/event-logs',
  getParentRoute: () => AppRoute,
} as any)
const AppDomainsRoute = AppDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AppRoute,
} as any)
const AppDomainCredentialsRoute = AppDomainCredentialsRouteImport.update({
  id: '/domain-credentials',
  path: '/domain-credentials',
  getParentRoute: () => AppRoute,
} as any)
const AppDatabasesRoute = AppDatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCronsRoute = AppCronsRouteImport.update({
  id: '/crons',
  path: '/crons',
  getParentRoute: () => AppRoute,
} as any)
const AppCloudProvidersRoute = AppCloudProvidersRouteImport.update({
  id: '/cloud-providers',
  path: '/cloud-providers',
  getParentRoute: () => AppRoute,
} as any)
const AppBlockStoragesRoute = AppBlockStoragesRouteImport.update({
  id: '/block-storages',
  path: '/block-storages',
  getParentRoute: () => AppRoute,
} as any)
const AppServerDetailIdRoute = AppServerDetailIdRouteImport.update({
  id: '/server-detail/$id',
  path: '/server-detail/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPoliciesSlugRoute = AppPoliciesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppPoliciesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/block-storages': typeof AppBlockStoragesRoute
  '/cloud-providers': typeof AppCloudProvidersRoute
  '/crons': typeof AppCronsRoute
  '/dashboard': typeof AppDashboardRoute
  '/databases': typeof AppDatabasesRoute
  '/domain-credentials': typeof AppDomainCredentialsRoute
  '/domains': typeof AppDomainsRoute
  '/event-logs': typeof AppEventLogsRoute
  '/ips': typeof AppIpsRoute
  '/kubernetes': typeof AppKubernetesRoute
  '/policies': typeof AppPoliciesRouteWithChildren
  '/provider-credentials': typeof AppProviderCredentialsRoute
  '/resource-map': typeof AppResourceMapRoute
  '/server-groups': typeof AppServerGroupsRoute
  '/servers': typeof AppServersRoute
  '/settings': typeof AppSettingsRoute
  '/ssh-keys': typeof AppSshKeysRoute
  '/stats': typeof AppStatsRoute
  '/sync': typeof AppSyncRoute
  '/users': typeof AppUsersRoute
  '/users-groups': typeof AppUsersGroupsRoute
  '/policies/$slug': typeof AppPoliciesSlugRoute
  '/server-detail/$id': typeof AppServerDetailIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/block-storages': typeof AppBlockStoragesRoute
  '/cloud-providers': typeof AppCloudProvidersRoute
  '/crons': typeof AppCronsRoute
  '/dashboard': typeof AppDashboardRoute
  '/databases': typeof AppDatabasesRoute
  '/domain-credentials': typeof AppDomainCredentialsRoute
  '/domains': typeof AppDomainsRoute
  '/event-logs': typeof AppEventLogsRoute
  '/ips': typeof AppIpsRoute
  '/kubernetes': typeof AppKubernetesRoute
  '/policies': typeof AppPoliciesRouteWithChildren
  '/provider-credentials': typeof AppProviderCredentialsRoute
  '/resource-map': typeof AppResourceMapRoute
  '/server-groups': typeof AppServerGroupsRoute
  '/servers': typeof AppServersRoute
  '/settings': typeof AppSettingsRoute
  '/ssh-keys': typeof AppSshKeysRoute
  '/stats': typeof AppStatsRoute
  '/sync': typeof AppSyncRoute
  '/users': typeof AppUsersRoute
  '/users-groups': typeof AppUsersGroupsRoute
  '/policies/$slug': typeof AppPoliciesSlugRoute
  '/server-detail/$id': typeof AppServerDetailIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/block-storages': typeof AppBlockStoragesRoute
  '/_app/cloud-providers': typeof AppCloudProvidersRoute
  '/_app/crons': typeof AppCronsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/databases': typeof AppDatabasesRoute
  '/_app/domain-credentials': typeof AppDomainCredentialsRoute
  '/_app/domains': typeof AppDomainsRoute
  '/_app/event-logs': typeof AppEventLogsRoute
  '/_app/ips': typeof AppIpsRoute
  '/_app/kubernetes': typeof AppKubernetesRoute
  '/_app/policies': typeof AppPoliciesRouteWithChildren
  '/_app/provider-credentials': typeof AppProviderCredentialsRoute
  '/_app/resource-map': typeof AppResourceMapRoute
  '/_app/server-groups': typeof AppServerGroupsRoute
  '/_app/servers': typeof AppServersRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/ssh-keys': typeof AppSshKeysRoute
  '/_app/stats': typeof AppStatsRoute
  '/_app/sync': typeof AppSyncRoute
  '/_app/users': typeof AppUsersRoute
  '/_app/users-groups': typeof AppUsersGroupsRoute
  '/_app/policies/$slug': typeof AppPoliciesSlugRoute
  '/_app/server-detail/$id': typeof AppServerDetailIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/block-storages'
    | '/cloud-providers'
    | '/crons'
    | '/dashboard'
    | '/databases'
    | '/domain-credentials'
    | '/domains'
    | '/event-logs'
    | '/ips'
    | '/kubernetes'
    | '/policies'
    | '/provider-credentials'
    | '/resource-map'
    | '/server-groups'
    | '/servers'
    | '/settings'
    | '/ssh-keys'
    | '/stats'
    | '/sync'
    | '/users'
    | '/users-groups'
    | '/policies/$slug'
    | '/server-detail/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/setup'
    | '/block-storages'
    | '/cloud-providers'
    | '/crons'
    | '/dashboard'
    | '/databases'
    | '/domain-credentials'
    | '/domains'
    | '/event-logs'
    | '/ips'
    | '/kubernetes'
    | '/policies'
    | '/provider-credentials'
    | '/resource-map'
    | '/server-groups'
    | '/servers'
    | '/settings'
    | '/ssh-keys'
    | '/stats'
    | '/sync'
    | '/users'
    | '/users-groups'
    | '/policies/$slug'
    | '/server-detail/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/setup'
    | '/_app/block-storages'
    | '/_app/cloud-providers'
    | '/_app/crons'
    | '/_app/dashboard'
    | '/_app/databases'
    | '/_app/domain-credentials'
    | '/_app/domains'
    | '/_app/event-logs'
    | '/_app/ips'
    | '/_app/kubernetes'
    | '/_app/policies'
    | '/_app/provider-credentials'
    | '/_app/resource-map'
    | '/_app/server-groups'
    | '/_app/servers'
    | '/_app/settings'
    | '/_app/ssh-keys'
    | '/_app/stats'
    | '/_app/sync'
    | '/_app/users'
    | '/_app/users-groups'
    | '/_app/policies/$slug'
    | '/_app/server-detail/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users-groups': {
      id: '/_app/users-groups'
      path: '/users-groups'
      fullPath: '/users-groups'
      preLoaderRoute: typeof AppUsersGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sync': {
      id: '/_app/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof AppSyncRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stats': {
      id: '/_app/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ssh-keys': {
      id: '/_app/ssh-keys'
      path: '/ssh-keys'
      fullPath: '/ssh-keys'
      preLoaderRoute: typeof AppSshKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/servers': {
      id: '/_app/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof AppServersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/server-groups': {
      id: '/_app/server-groups'
      path: '/server-groups'
      fullPath: '/server-groups'
      preLoaderRoute: typeof AppServerGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resource-map': {
      id: '/_app/resource-map'
      path: '/resource-map'
      fullPath: '/resource-map'
      preLoaderRoute: typeof AppResourceMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/provider-credentials': {
      id: '/_app/provider-credentials'
      path: '/provider-credentials'
      fullPath: '/provider-credentials'
      preLoaderRoute: typeof AppProviderCredentialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policies': {
      id: '/_app/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof AppPoliciesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kubernetes': {
      id: '/_app/kubernetes'
      path: '/kubernetes'
      fullPath: '/kubernetes'
      preLoaderRoute: typeof AppKubernetesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ips': {
      id: '/_app/ips'
      path: '/ips'
      fullPath: '/ips'
      preLoaderRoute: typeof AppIpsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/event-logs': {
      id: '/_app/event-logs'
      path: '/event-logs'
      fullPath: '/event-logs'
      preLoaderRoute: typeof AppEventLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/domains': {
      id: '/_app/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof AppDomainsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/domain-credentials': {
      id: '/_app/domain-credentials'
      path: '/domain-credentials'
      fullPath: '/domain-credentials'
      preLoaderRoute: typeof AppDomainCredentialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/databases': {
      id: '/_app/databases'
      path: '/databases'
      fullPath: '/databases'
      preLoaderRoute: typeof AppDatabasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crons': {
      id: '/_app/crons'
      path: '/crons'
      fullPath: '/crons'
      preLoaderRoute: typeof AppCronsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cloud-providers': {
      id: '/_app/cloud-providers'
      path: '/cloud-providers'
      fullPath: '/cloud-providers'
      preLoaderRoute: typeof AppCloudProvidersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/block-storages': {
      id: '/_app/block-storages'
      path: '/block-storages'
      fullPath: '/block-storages'
      preLoaderRoute: typeof AppBlockStoragesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/server-detail/$id': {
      id: '/_app/server-detail/$id'
      path: '/server-detail/$id'
      fullPath: '/server-detail/$id'
      preLoaderRoute: typeof AppServerDetailIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/policies/$slug': {
      id: '/_app/policies/$slug'
      path: '/$slug'
      fullPath: '/policies/$slug'
      preLoaderRoute: typeof AppPoliciesSlugRouteImport
      parentRoute: typeof AppPoliciesRoute
    }
  }
}

interface AppPoliciesRouteChildren {
  AppPoliciesSlugRoute: typeof AppPoliciesSlugRoute
}

const AppPoliciesRouteChildren: AppPoliciesRouteChildren = {
  AppPoliciesSlugRoute: AppPoliciesSlugRoute,
}

const AppPoliciesRouteWithChildren = AppPoliciesRoute._addFileChildren(
  AppPoliciesRouteChildren,
)

interface AppRouteChildren {
  AppBlockStoragesRoute: typeof AppBlockStoragesRoute
  AppCloudProvidersRoute: typeof AppCloudProvidersRoute
  AppCronsRoute: typeof AppCronsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDatabasesRoute: typeof AppDatabasesRoute
  AppDomainCredentialsRoute: typeof AppDomainCredentialsRoute
  AppDomainsRoute: typeof AppDomainsRoute
  AppEventLogsRoute: typeof AppEventLogsRoute
  AppIpsRoute: typeof AppIpsRoute
  AppKubernetesRoute: typeof AppKubernetesRoute
  AppPoliciesRoute: typeof AppPoliciesRouteWithChildren
  AppProviderCredentialsRoute: typeof AppProviderCredentialsRoute
  AppResourceMapRoute: typeof AppResourceMapRoute
  AppServerGroupsRoute: typeof AppServerGroupsRoute
  AppServersRoute: typeof AppServersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSshKeysRoute: typeof AppSshKeysRoute
  AppStatsRoute: typeof AppStatsRoute
  AppSyncRoute: typeof AppSyncRoute
  AppUsersRoute: typeof AppUsersRoute
  AppUsersGroupsRoute: typeof AppUsersGroupsRoute
  AppServerDetailIdRoute: typeof AppServerDetailIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBlockStoragesRoute: AppBlockStoragesRoute,
  AppCloudProvidersRoute: AppCloudProvidersRoute,
  AppCronsRoute: AppCronsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDatabasesRoute: AppDatabasesRoute,
  AppDomainCredentialsRoute: AppDomainCredentialsRoute,
  AppDomainsRoute: AppDomainsRoute,
  AppEventLogsRoute: AppEventLogsRoute,
  AppIpsRoute: AppIpsRoute,
  AppKubernetesRoute: AppKubernetesRoute,
  AppPoliciesRoute: AppPoliciesRouteWithChildren,
  AppProviderCredentialsRoute: AppProviderCredentialsRoute,
  AppResourceMapRoute: AppResourceMapRoute,
  AppServerGroupsRoute: AppServerGroupsRoute,
  AppServersRoute: AppServersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSshKeysRoute: AppSshKeysRoute,
  AppStatsRoute: AppStatsRoute,
  AppSyncRoute: AppSyncRoute,
  AppUsersRoute: AppUsersRoute,
  AppUsersGroupsRoute: AppUsersGroupsRoute,
  AppServerDetailIdRoute: AppServerDetailIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
