import { createStitches } from '@stitches/react';

export const {
  styled,
  css,
  globalCss,
  keyframes,
  theme,
  createTheme,
  config,
} = createStitches({
  theme: {
    colors: {
      bgBase: 'var(--bg-base)',
      bgS1: 'var(--bg-s1)',
      bgS2: 'var(--bg-s2)',
      bgS3: 'var(--bg-s3)',
      border: 'var(--bd)',
      borderStrong: 'var(--bd-strong)',
      tx1: 'var(--tx1)',
      tx2: 'var(--tx2)',
      tx3: 'var(--tx3)',
      txd: 'var(--txd)',
      accent: 'var(--ac)',
      accentHover: 'var(--ach)',
      accentSelected: 'var(--acs)',
      accentBg: 'var(--ac-bg)',
      accentBorder: 'var(--ac-bd)',
      accentGlow: 'var(--ac-glow)',
      statusGreen: 'var(--sg)',
      statusGreenBg: 'var(--sg-bg)',
      statusGreenBorder: 'var(--sg-bd)',
      statusGreenGlow: 'var(--sg-glow)',
      statusRed: 'var(--sr)',
      statusRedBg: 'var(--sr-bg)',
      statusRedBorder: 'var(--sr-bd)',
      statusYellow: 'var(--sy)',
      statusYellowBg: 'var(--sy-bg)',
      statusYellowBorder: 'var(--sy-bd)',
      statusGray: 'var(--sgr)',
      statusGrayBg: 'var(--sgr-bg)',
      statusGrayBorder: 'var(--sgr-bd)',
      glassBg: 'var(--glass-bg)',
      glassBorder: 'var(--glass-bd)',
      btnFg: 'var(--btn-primary-fg)',
      sidebarFrom: 'var(--sidebar-from)',
      sidebarTo: 'var(--sidebar-to)',
      headerBg: 'var(--header-bg)',
      navActiveBg: 'var(--nav-active-bg)',
      navActiveBorder: 'var(--nav-active-bd)',
      cardHoverBorder: 'var(--card-hover-bd)',
    },
    space: {
      1: '0.25rem',
      2: '0.5rem',
      3: '0.75rem',
      4: '1rem',
      5: '1.25rem',
      6: '1.5rem',
      8: '2rem',
      10: '2.5rem',
      12: '3rem',
    },
    fontSizes: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
    },
    fonts: {
      sans: "'DM Sans', system-ui, sans-serif",
      display: "'Cormorant Garamond', Georgia, serif",
    },
    radii: {
      sm: '2px',
      md: '3px',
      lg: '4px',
      xl: '6px',
      full: '9999px',
    },
    shadows: {
      card: 'var(--shadow-card)',
      glass: 'var(--shadow-glass)',
      modal: 'var(--shadow-modal)',
    },
  },
  media: {
    sm: '(min-width: 640px)',
    md: '(min-width: 768px)',
    lg: '(min-width: 1024px)',
    xl: '(min-width: 1280px)',
  },
});

export const pulseRing = keyframes({
  '0%': {
    boxShadow: '0 0 0 0 rgba(34, 197, 94, 0.4)',
  },
  '70%': {
    boxShadow: '0 0 0 6px rgba(34, 197, 94, 0)',
  },
  '100%': {
    boxShadow: '0 0 0 0 rgba(34, 197, 94, 0)',
  },
});
